CREATE TABLE [dbo].[hbhousehold](
	[claim_id] [int] NULL,
	[house_id] [smallint] NULL,
	[last_upd] [int] NULL,
	[from_date] [datetime2](7) NULL,
	[to_date] [datetime2](7) NULL,
	[inc_supp_ind] [smallint] NULL,
	[claim_type_ind] [smallint] NULL,
	[addr1] [nvarchar](35) NULL,
	[addr2] [nvarchar](35) NULL,
	[addr3] [nvarchar](32) NULL,
	[addr4] [nvarchar](32) NULL,
	[post_code] [nvarchar](10) NULL,
	[find_addr1] [nvarchar](16) NULL,
	[find_addr2] [nvarchar](16) NULL,
	[reassess_ind] [smallint] NULL,
	[srr_exempt] [smallint] NULL,
	[lp_protect_ind] [smallint] NULL,
	[cbl_protect_ind] [smallint] NULL,
	[bereavement_override] [smallint] NULL,
	[is_claim_date] [datetime2](7) NULL,
	[is_award_date] [datetime2](7) NULL,
	[is_reject_date] [datetime2](7) NULL,
	[uprn] [nvarchar](12) NULL,
	[away_address_ind] [smallint] NULL,
	[shared_accom_ind] [smallint] NULL,
	[is_mid_week_split] [smallint] NULL,
	[locality_code] [nvarchar](6) NULL,
	[districtmove_id] [int] NULL,
	[dmp_ind] [smallint] NULL,
	[group_id] [int] NULL,
	[ben_cap_level_ind] [smallint] NULL,
	[uc_dhp_ind] [smallint] NULL,
	[category_ind] [int] NULL,
	[fa_ind] [int] NULL
) 

CREATE TABLE [dbo].[hbmember](
	[claim_id] [int] NULL,
	[house_id] [smallint] NULL,
	[member_id] [smallint] NULL,
	[person_ref] [int] NULL,
	[name] [nvarchar](32) NULL,
	[surname] [nvarchar](32) NULL,
	[title] [nvarchar](4) NULL,
	[forename] [nvarchar](32) NULL,
	[find_name] [nvarchar](32) NULL,
	[type] [smallint] NULL,
	[birth_date] [datetime2](7) NULL,
	[gender] [smallint] NULL,
	[carer_ind] [smallint] NULL,
	[disable_ind] [smallint] NULL,
	[hospital_ind] [smallint] NULL,
	[meals_ind] [smallint] NULL,
	[shared_percent] [real] NULL,
	[student_ind] [smallint] NULL,
	[hours_worked] [nvarchar](6) NULL,
	[cared_for_ind] [smallint] NULL,
	[school_ind] [smallint] NULL,
	[nino] [nvarchar](10) NULL,
	[age_ind] [smallint] NULL,
	[self_empl_ind] [smallint] NULL,
	[incapable_of_work] [smallint] NULL,
	[weeks_28] [smallint] NULL,
	[weeks_52] [smallint] NULL,
	[hold_risk_sub_grp_cas] [datetime2](7) NULL,
	[residential_acc] [smallint] NULL,
	[bereaved_date] [datetime2](7) NULL,
	[bea_end_date] [datetime2](7) NULL,
	[fepow_disregard] [numeric](14, 2) NULL,
	[mat_leave_ccp_ind] [smallint] NULL,
	[holocaust_disregard] [numeric](14, 2) NULL,
	[srplumpsum_disregard] [numeric](14, 2) NULL,
	[chb_end_date] [datetime2](7) NULL,
	[deceased_date] [datetime2](7) NULL,
	[eight_week_ind] [smallint] NULL,
	[num_child_under_1] [smallint] NULL,
	[num_child_under_16] [smallint] NULL,
	[num_youth_16_18] [smallint] NULL,
	[num_dis_child_prem] [smallint] NULL,
	[num_enhan_dis_child_prem] [smallint] NULL,
	[ccp_prison_hosp_ind] [smallint] NULL,
	[ccp_rem_work_ind] [smallint] NULL,
	[advantageous_change_ind] [smallint] NULL,
	[not_payable_ind] [smallint] NULL,
	[non_dep_gc_sc_ind] [smallint] NULL,
	[non_dep_easement_ind] [smallint] NULL,
	[sanction_rate] [numeric](14, 2) NULL,
	[easement_date] [datetime2](7) NULL,
	[disregard_50] [smallint] NULL,
	[non_dep_grp] [smallint] NULL,
	[party_ref] [int] NULL,
	[spd_ignore_date] [datetime2](7) NULL,
	[unique_pupil_num] [nvarchar](15) NULL,
	[severely_mentally_impaired_ind] [smallint] NULL,
	[period_sanction] [int] NULL,
	[sanction_type] [int] NULL,
	[sanction_rate_type] [int] NULL
) 







